### PR TITLE
Avoid repeated records when generating changesets using `since`

### PR DESCRIPTION
**Pull request by manish-raje**
Kindly consider adding the records after the HLC timestamp.

### CODE REVIEW

**Comment by cachapa** [comment]
What is the reasoning for this? It seems to just be `recordMap()` using `<=` instead of `<`.

**Comment by manish-raje** [comment]
Hi @cachapa, I was looking at the Hive CRDT to let me know the Hive records updated after the canonical time HLC timestamp during application run, but there was no good way to handle it. If you can recommend, a good way to handle it.

**Comment by manish-raje** [comment]
So to give use case clarity -

I have record with key A to store the value 2 and B to store the value 3. And I close the mobile application. During the close, I remember the last canonical timestamp to know when we launch the application next time what are the records updated after the last launch.

The application really wanted to know whether there are any updates to the records stored in Hive.

When I next time launch the application, I find the record B is updated since the last canonical timestamp. But there is no update really to record B. The expectation was an empty result.

Of course when the application was in background and got the record C with value 4. And we stored it in the Hive CRDT, I want it to be returned as the updated record after the last canonical timestamp stored in the application during the launch.

**Comment by cachapa** [comment]
I see the problem. You're right that the logic is incorrect, and in fact I fixed it in [sql_crdt](https://github.com/cachapa/sql_crdt) and [crdt_sync](https://github.com/cachapa/crdt_sync).

But I think the correct approach here is to fix `recordMap` rather than adding a new method.
If you want to do it, I'd be happy to approve.

**Comment by manish-raje** [comment]
OK I see the getChangeSet function in sql_crdt actually only returns the data modified after the `modifiedSince`.

I will make the required fix and update the test case.

**Comment by manish-raje** [comment]
Kindly review the updated version.

**Comment by cachapa** [comment]
Thanks!

**Comment by cachapa** [comment]
Sorry, forgot to release a new version. It's up on pub.dev now: 2.0.4

**Pull request merged**
